MVC/Models/mvcAbonoRetiroModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace MVC.Models
{
    public class mvcAbonoRetiroModel
    {   
        [Required]
        public string NroCuenta { get; set; }
        [Required]
        public decimal Monto { get; set; }
    }
}

MVC/Models/mvcCuentaDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class mvcCuentaDetailModel
    {
        public mvcCuentaModel cuenta { get; set; }
        public IEnumerable<mvcMovimientoModel> movimientosList { get; set; }
    }
}

MVC/Models/mvcCuentaModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class mvcCuentaModel
    {
        [Required (ErrorMessage = "Debe llenarse el campo")]
        [StringLength(14, MinimumLength = 13, ErrorMessage = "El número de cuenta no es válido")]
        public string NroCuenta { get; set; }
        public string Tipo { get; set; }
        public Moneda Moneda { get; set; }

        [Required (ErrorMessage ="Debe llenarse el campo")]
        [StringLength(40, ErrorMessage ="El campo no puede exceder de 40 caracteres")]
        public string Nombre { get; set; }

        public decimal Saldo { get; set; }
    }
    
    public enum Moneda
    {
        BOL,
        DOL
    }
}

MVC/Models/mvcMovimientoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class mvcMovimientoModel
    {
        public string NroCuenta { get; set; }
        public DateTime Fecha { get; set; }
        public char Tipo { get; set; }
        public decimal Importe { get; set; }
    }
}

MVC/Models/mvcTransactionModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class mvcTransactionModel
    {
        [Required]
        public string CuentaOrigen { get; set; }
        [Required]
        public string CuentaDestino { get; set; }

        [Required]
        public decimal Monto { get; set; }
    }
}

MVC/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using MVC.Models;

namespace MVC.Controllers
{
    public class BankController : Controller
    {
        // GET: Bank
        public ActionResult Index()
        {
            IEnumerable<mvcCuentaModel> cuentasList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Cuenta").Result;
            cuentasList = response.Content.ReadAsAsync<IEnumerable<mvcCuentaModel>>().Result;    
            return View(cuentasList);
        }

        public ActionResult NuevaCuenta()
        {
            return View(new mvcCuentaModel());
        }

        [HttpPost]
        public ActionResult NuevaCuenta(mvcCuentaModel cuenta)
        {
            List<SelectListItem> monedas = new List<SelectListItem>();
            monedas.Add(new SelectListItem { Text = "Bolivianos", Value = "BOL" });
            monedas.Add(new SelectListItem { Text = "Dolares", Value = "DOL" });

            ViewBag.MonedasType = monedas;
            HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Cuenta", cuenta).Result;
            return RedirectToAction("Index");
        }

        public ActionResult Movimientos(string id)
        {
            mvcCuentaDetailModel cuentaDetallada = new mvcCuentaDetailModel();
            
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Movimiento/" + id).Result;
            HttpResponseMessage response2 = GlobalVariables.WebApiClient.GetAsync("Cuenta/" + id).Result;
            cuentaDetallada.movimientosList = response.Content.ReadAsAsync<IEnumerable<mvcMovimientoModel>>().Result;
            cuentaDetallada.cuenta = response2.Content.ReadAsAsync<mvcCuentaModel>().Result;
            return View(cuentaDetallada);
        }

        public ActionResult Transaccion()
        {
            List<string> cuentasList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("NroCuenta").Result;
            cuentasList = response.Content.ReadAsAsync<List<string>>().Result;
            ViewBag.data = cuentasList;
            return View(new mvcTransactionModel());
        }

        [HttpPost]
        public ActionResult Transaccion(mvcTransactionModel transaccion)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Transaccion", transaccion).Result;
            return RedirectToAction("Index");
        }

        public ActionResult Operacion()
        {
            List<string> cuentasList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("NroCuenta").Result;
            cuentasList = response.Content.ReadAsAsync<List<string>>().Result;
            ViewBag.data = cuentasList;
            return View(new mvcAbonoRetiroModel());
        }

        [HttpPost]
        public ActionResult Operacion(mvcAbonoRetiroModel operacion, string submitButton)
        {
            if (submitButton.Equals("Abono"))
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Abono", operacion).Result;
            } else if (submitButton.Equals("Retiro"))
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Retiro", operacion).Result;
            }
            return RedirectToAction("Index");
        }

       
    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/Views/Bank/Index.cshtml
@model IEnumerable<MVC.Models.mvcCuentaModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("NuevaCuenta", "Bank")" class="btn btn-default"><i class="fa fa-plus"></i>Cuenta Nueva</a>
    <a href="@Url.Action("Transaccion", "Bank")" class="btn btn-default"><i class="fa fa-plus"></i>Transaccion</a>
    <a href="@Url.Action("Operacion", "Bank")" class="btn btn-default"><i class="fa fa-plus"></i>Abono / Retiro</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NroCuenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Moneda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Saldo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NroCuenta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tipo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moneda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Saldo)
        </td>
        <td>
            <a href="@Url.Action("Movimientos", "Bank", new { id = item.NroCuenta })" class="btn btn-default">Mov.</a>
            
        </td>
    </tr>
}

</table>

MVC/Views/Bank/Movimientos.cshtml
@using MVC.Models

@model mvcCuentaDetailModel

@{
    ViewBag.Title = "Movimientos";
}

<div class="list-group">
    @Html.LabelFor(model => model.cuenta.Nombre, "Nombre")
    @Html.DisplayFor(model => model.cuenta.Nombre)
</div>

<div class="list-group">
    @Html.LabelFor(model => model.cuenta.NroCuenta, "Numero de cuenta")
    @Html.DisplayFor(model => model.cuenta.NroCuenta)
</div>
<div class="list-group">
    @Html.LabelFor(model => model.cuenta.Saldo, "Saldo")
    @Html.DisplayFor(model => model.cuenta.Saldo)
</div>
<div class="list-group">
    @Html.LabelFor(model => model.cuenta.Moneda, "Moneda")
    @Html.DisplayFor(model => model.cuenta.Moneda)
</div>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.movimientosList)
            </th>

        </tr>

        @foreach (var item in Model.movimientosList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NroCuenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Importe)
                </td>
            </tr>
        }

    </table>

MVC/Views/Bank/NuevaCuenta.cshtml
@using MVC.Models

@model mvcCuentaModel

@{
    ViewBag.Title = "NuevaCuenta";
}

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Saldo)
        @Html.HiddenFor(model => model.Tipo)

        <div class="form-group">
            @Html.LabelFor(model => model.NroCuenta, "Numero de Cuenta")
            
            @Html.EditorFor(model => model.NroCuenta)
            @Html.ValidationMessageFor(model => model.NroCuenta)

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moneda, "Seleccione Moneda")
            @Html.DropDownListFor(model => model.Moneda, new SelectList(Enum.GetValues(typeof(Moneda))))
            @Html.ValidationMessageFor(model => model.Moneda)

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)

        </div>

        <div class="form-group">
            <input type="submit" value="Crear" class="btn button" />
            <input type="reset" value="Borrar" class="btn button" />
        </div>
    }

</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    }

MVC/Views/Bank/Operacion.cshtml
@using MVC.Models

@model mvcAbonoRetiroModel

@{
    ViewBag.Title = "Operacion";
}

<h2>Operacion</h2>

<div class="form-body">
    @using (Html.BeginForm())
    {
        <div class="form-group">
            @Html.LabelFor(model => model.NroCuenta, "Seleccione Cuenta Origen")
            @Html.DropDownListFor(model => model.NroCuenta, new SelectList(ViewBag.data))
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, "Saldo")
            @Html.EditorFor(model => model.Monto)
            @Html.ValidationMessageFor(model => model.Monto)

        </div>

        <div class="form-group">
            <input type="submit" name="submitButton" value="Abono" class="btn button" />
            <input type="reset" name="submitButton" value="Retiro" class="btn button" />
        </div>
    }

</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

MVC/Views/Bank/Transaccion.cshtml
@using MVC.Models

@model mvcTransactionModel

@{
    ViewBag.Title = "Transaccion";
}

<h2>Transaccion</h2>

<div class="form-body">
    @using (Html.BeginForm())
    {
        <div class="form-group">
            @Html.LabelFor(model => model.CuentaOrigen, "Seleccione Cuenta Origen")
            @Html.DropDownListFor(model => model.CuentaOrigen, new SelectList(ViewBag.data))
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuentaDestino, "Seleccione Cuenta Destino")
            @Html.DropDownListFor(model => model.CuentaDestino, new SelectList(ViewBag.data))
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, "Saldo")
            @Html.EditorFor(model => model.Monto)
            @Html.ValidationMessageFor(model => model.Monto)

        </div>

        <div class="form-group">
            <input type="submit" value="Transferir" class="btn button" />
            <input type="reset" value="Borrar" class="btn button" />
        </div>
    }

</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BCP Bank System", "Index", "Bank", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Roberto Pablo Cuevas Pinto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>